/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve.kotlin.postgres.keys


import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.mcve.kotlin.postgres.tables.Segment
import org.jooq.mcve.kotlin.postgres.tables.records.SegmentRecord



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val SEGMENT_CODE_KEY: UniqueKey<SegmentRecord> = Internal.createUniqueKey(Segment.SEGMENT, DSL.name("segment_code_key"), arrayOf(Segment.SEGMENT.CODE), true)
val SEGMENT_PKEY: UniqueKey<SegmentRecord> = Internal.createUniqueKey(Segment.SEGMENT, DSL.name("segment_pkey"), arrayOf(Segment.SEGMENT.ID), true)
