/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve.kotlin.postgres.tables.references


import org.jooq.mcve.kotlin.postgres.tables.Segment



/**
 * The table <code>mcve.segment</code>.
 */
val SEGMENT: Segment = Segment.SEGMENT
