/*
 * This file is generated by jOOQ.
 */
package org.jooq.mcve.kotlin.postgres


import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl
import org.jooq.mcve.kotlin.postgres.tables.Segment


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Mcve : SchemaImpl("mcve", DefaultCatalog.DEFAULT_CATALOG) {
    public companion object {

        /**
         * The reference instance of <code>mcve</code>
         */
        val MCVE: Mcve = Mcve()
    }

    /**
     * The table <code>mcve.segment</code>.
     */
    val SEGMENT: Segment get() = Segment.SEGMENT

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        Segment.SEGMENT
    )
}
